"""Obsidian views: the Bases and the notes that embed them, and a page per room."""

from __future__ import annotations

from pathlib import Path

import pytest
from homeassistant.core import HomeAssistant
from homeassistant.helpers import area_registry as ar
from pytest_homeassistant_custom_component.common import MockConfigEntry

from custom_components.notes_vault.const import (
    CONF_BASE_FOLDER,
    CONF_GENERATE_VIEWS,
    DEFAULT_OPTIONS,
)
from custom_components.notes_vault.manager import NotesVault
from custom_components.notes_vault.vault import parse_note

BASE = "Home Assistant"
BASES = f"{BASE}/Bases"


async def test_views_are_written_with_their_paths(
    hass: HomeAssistant, manager: NotesVault, vault_dir: Path
) -> None:
    """Every view and its note is written, with the vault's own paths filled in."""
    for name in (
        "Rooms",
        "Devices",
        "Automations",
        "Integrations",
        "Batteries",
        "Cleanup",
    ):
        assert (vault_dir / f"{BASES}/{name}.base").is_file()
        note = (vault_dir / f"{BASE}/{name}.md").read_text()
        assert f"![[{BASES}/{name}.base" in note
        # Written once and then the user's: no generated-file warning.
        assert "[!note]" not in note
    assert (vault_dir / f"{BASES}/Room.base").is_file()

    recent = (vault_dir / f"{BASES}/Recently changed.base").read_text()
    assert f'"{BASE}/Templates"' in recent
    assert f'"{BASE}/Index.md"' in recent
    assert "{{" not in recent


async def test_views_are_written_once(
    hass: HomeAssistant,
    config_entry: MockConfigEntry,
    manager: NotesVault,
    vault_dir: Path,
) -> None:
    """A view the user changed or deleted stays that way across restarts."""
    tuned = vault_dir / f"{BASES}/Automations.base"
    tuned.write_text("views: []\n")
    deleted = vault_dir / f"{BASE}/Batteries.md"
    deleted.unlink()

    assert await hass.config_entries.async_reload(config_entry.entry_id)
    await hass.async_block_till_done()

    assert tuned.read_text() == "views: []\n"
    assert not deleted.exists()


async def test_room_pages_follow_the_areas(
    hass: HomeAssistant, home: dict, manager: NotesVault, vault_dir: Path
) -> None:
    """One page per area, renamed and removed with it."""
    await manager.async_sync()
    page = vault_dir / f"{BASES}/Rooms/Kitchen.md"
    note = parse_note(page.read_text())
    assert note.frontmatter == {
        "ha_type": "room",
        "ha_id": home["area"].id,
        "area": f"[[{BASE}/Areas/Kitchen|Kitchen]]",
    }
    assert f"![[{BASES}/Room.base]]" in note.body
    assert "rewritten on every sync" in note.body
    assert f"[[{BASE}/Areas/Kitchen|Kitchen]] area" in note.body

    ar.async_get(hass).async_update(home["area"].id, name="Cucina")
    await manager.async_sync()
    assert not page.exists()
    renamed = parse_note((vault_dir / f"{BASES}/Rooms/Cucina.md").read_text())
    assert renamed.frontmatter["area"] == f"[[{BASE}/Areas/Cucina|Cucina]]"

    ar.async_get(hass).async_delete(home["area"].id)
    await manager.async_sync()
    assert list((vault_dir / f"{BASES}/Rooms").glob("*.md")) == []


async def test_views_stay_out_of_the_index_and_backlinks(
    hass: HomeAssistant, home: dict, manager: NotesVault, vault_dir: Path
) -> None:
    """The view notes and room pages aren't notes someone wrote, or mentions."""
    await manager.async_sync()
    await manager.async_write_index()
    index = (vault_dir / f"{BASE}/Index.md").read_text()
    assert "> [!note] Generated by Notes Vault" in index
    assert "Automations|" not in index
    assert "Bases/Rooms" not in index

    area = await manager.async_get_file(f"{BASE}/Areas/Kitchen.md")
    assert all("Bases/Rooms" not in b["path"] for b in area["backlinks"])


@pytest.mark.parametrize("options", [{**DEFAULT_OPTIONS, CONF_GENERATE_VIEWS: False}])
async def test_views_can_be_turned_off(
    hass: HomeAssistant, home: dict, manager: NotesVault, vault_dir: Path
) -> None:
    """With the option off, no views are written and no room pages kept."""
    await manager.async_sync()
    assert not (vault_dir / BASES).exists()
    assert not (vault_dir / f"{BASE}/Rooms.md").exists()


@pytest.mark.parametrize("options", [{**DEFAULT_OPTIONS, CONF_BASE_FOLDER: ""}])
async def test_views_at_the_top_level(
    hass: HomeAssistant, home: dict, manager: NotesVault, vault_dir: Path
) -> None:
    """Without a generated folder, the views sit at the top of the vault."""
    await manager.async_sync()
    assert (vault_dir / "Rooms.md").is_file()
    assert (vault_dir / "Bases/Rooms/Kitchen.md").is_file()
    recent = (vault_dir / "Bases/Recently changed.base").read_text()
    assert '"Templates"' in recent
    assert '"Index.md"' in recent
