#!/usr/bin/env python3
"""Generate the brand icon.

    python tools/make_icon.py

Writes `icon.svg` and renders every PNG size from it. The SVG is build output — change
this script and re-run it, never edit the SVG by hand, or the next run silently reverts
your edit.

The icon is a note page with a house on it: notes about the things in your home.
"""

from __future__ import annotations

import math
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

#: The artboard. Home Assistant only ever serves the 256 and 512 renders, but the source
#: is drawn at 1024 so the maths below is in round numbers.
SIZE = 1024

#: Apple's app-icon corner, as a fraction of the width, with Figma's equivalent
#: corner-smoothing value. These two numbers *are* the iOS icon shape; see squircle().
CORNER_RADIUS_RATIO = 0.2237
CORNER_SMOOTHING = 0.6


def squircle(size: float) -> str:
    """Return the iOS app-icon shape as an SVG path, inscribed in a `size` square.

    Not a superellipse. The obvious implementation — `|x|^n + |y|^n = 1` with n
    around 5 — is the shape most people mean by "squircle", but it is not the one
    Apple uses, and the difference is visible: a superellipse curves continuously
    everywhere, so the edges that should be flat bow outward. Side by side against
    a real app icon it reads as pillowed.

    Apple's mask is a *rounded rectangle with continuous curvature*, as produced by
    `UIBezierPath(roundedRect:cornerRadius:)`: genuinely straight edges, with the
    corner easing curvature in over a longer run than a circular arc would. This is
    the construction Figma exposes as "corner smoothing", at the iOS values.

    A circular corner is still wrong for the reason you would expect — curvature
    jumps from 0 to 1/r at the join — but the fix is smoothing the transition, not
    abandoning the straight edge.
    """
    radius = size * CORNER_RADIUS_RATIO
    budget = size / 2

    # Keep the corner inside the space available to it; without the cap a large
    # radius yields a self-intersecting path rather than a clipped one.
    smoothing = min(CORNER_SMOOTHING, budget / radius - 1)
    p = min((1 + smoothing) * radius, budget)

    arc_measure = math.radians(90 * (1 - smoothing))
    arc = math.sin(arc_measure / 2) * radius * math.sqrt(2)

    angle_alpha = (math.pi / 2 - arc_measure) / 2
    angle_beta = math.radians(45 * smoothing)
    c = radius * math.tan(angle_alpha / 2) * math.cos(angle_beta)
    d = c * math.tan(angle_beta)

    # The straight run into each corner splits 2:1 between the two off-curve
    # control points. That ratio is what ramps curvature smoothly.
    b = (p - arc - c - d) / 3
    a = 2 * b

    def f(value: float) -> str:
        return f"{value:.4f}"

    return " ".join(
        [
            f"M {f(size - p)} 0",
            f"c {f(a)} 0 {f(a + b)} 0 {f(a + b + c)} {f(d)}",
            f"a {f(radius)} {f(radius)} 0 0 1 {f(arc)} {f(arc)}",
            f"c {f(d)} {f(c)} {f(d)} {f(b + c)} {f(d)} {f(a + b + c)}",
            f"L {f(size)} {f(size - p)}",
            f"c 0 {f(a)} 0 {f(a + b)} {f(-d)} {f(a + b + c)}",
            f"a {f(radius)} {f(radius)} 0 0 1 {f(-arc)} {f(arc)}",
            f"c {f(-c)} {f(d)} {f(-(b + c))} {f(d)} {f(-(a + b + c))} {f(d)}",
            f"L {f(p)} {f(size)}",
            f"c {f(-a)} 0 {f(-(a + b))} 0 {f(-(a + b + c))} {f(-d)}",
            f"a {f(radius)} {f(radius)} 0 0 1 {f(-arc)} {f(-arc)}",
            f"c {f(-d)} {f(-c)} {f(-d)} {f(-(b + c))} {f(-d)} {f(-(a + b + c))}",
            f"L 0 {f(p)}",
            f"c 0 {f(-a)} 0 {f(-(a + b))} {f(d)} {f(-(a + b + c))}",
            f"a {f(radius)} {f(radius)} 0 0 1 {f(arc)} {f(-arc)}",
            f"c {f(c)} {f(-d)} {f(b + c)} {f(-d)} {f(a + b + c)} {f(-d)}",
            "Z",
        ]
    )


def build() -> str:
    """Return the SVG source: a note page with a house on it, on a violet tile."""
    return f"""\
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {SIZE} {SIZE}" \
width="{SIZE}" height="{SIZE}">
  <title>Notes Vault</title>

  <!-- Generated by tools/make_icon.py. Do not edit; re-run the script. -->

  <defs>
    <linearGradient id="tile" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#7B5CF0"/>
      <stop offset="1" stop-color="#4A2FB8"/>
    </linearGradient>
  </defs>

  <path d="{squircle(SIZE)}" fill="url(#tile)"/>

  <path d="M 348 196 H 604 L 740 332 V 772 Q 740 828 684 828 H 348 \
Q 292 828 292 772 V 252 Q 292 196 348 196 Z" fill="#FFFFFF"/>
  <path d="M 604 196 V 284 Q 604 332 652 332 H 740 Z" fill="#D8CEFF"/>

  <g fill="none" stroke="#5B3FD6" stroke-width="44" stroke-linecap="round" \
stroke-linejoin="round">
    <path d="M 388 468 L 516 364 L 644 468"/>
    <path d="M 428 440 V 548 H 604 V 440"/>
  </g>

  <g stroke="#C9BCF7" stroke-width="36" stroke-linecap="round">
    <path d="M 392 640 H 640"/>
    <path d="M 392 724 H 572"/>
  </g>
</svg>
"""


def main() -> None:
    """Write the SVG and render the PNGs beside it."""
    (component,) = (ROOT / "custom_components").iterdir()
    source = component / "brand" / "icon.svg"
    source.write_text(build())
    print(f"{source}")

    subprocess.run(
        [sys.executable, str(ROOT / "tools" / "render_brand.py"), str(source)],
        check=True,
    )


if __name__ == "__main__":
    main()
